# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

#pool:
#  vmImage: 'ubuntu-latest'

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'


schedules:
- cron: "0 23 * * Sun"
  displayName: Weekly Sunday disable Developer Write Access
  branches:
    exclude:
      - 
  always: true

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $uri = "https://api.github.com/orgs/PSW-2020-ORG9/teams/developers/repos/PSW-2020-ORG9/test"
      $header = @{Authorization="Bearer $env:TOKEN"; Accept="application/vnd.github.inertia-preview+json"}
      if([int]$(Get-Date -UFormat %V) % 2 -eq 1){
        Invoke-RestMethod -Method 'Put' -Uri $uri -Headers $header -Body '{"permission":"pull"}'
      }
  env:
    TOKEN: $(token)
#- task: PowerShell@2
#  inputs:
#    filePath: 'devops/script.ps1'
#  env:
#    TOKEN: $(token)