# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

#pool:
#  vmImage: 'ubuntu-latest'

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'


schedules:
- cron: "0 0 * * 6"
  displayName: Weekly Sunday disable Developer Write Access
  branches:
    exclude: 
    - master
  always: true

steps:
- task: PowerShell@2
  env:
    TOKEN: $(token)
  inputs:
    targetType: 'inline'
    script: 
      $uri = "https://api.github.com/orgs/PSW-2020-ORG9/teams/developers/repos/PSW-2020-ORG9/test"
      $headers = @{Authorization="Bearer ${env:TOKEN}"; Accept="application/vnd.github.inertia-preview+json"}
      Invoke-RestMethod -Method 'Put' -Uri $uri -Headers $headers -Body '{"permission":"pull"}'